---
os: linux
language: python
cache: pip

git:
  submodules: true

jobs:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.7"
    env: TOXENV=py37
  - python: "3.9"
    env: TOXENV=py39

install:
- pip install --ignore-installed --upgrade setuptools pip tox

script:
- cd library
- tox -vv
