---
os: linux
language: python
cache: pip

git:
  submodules: true

jobs:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.5"
    env: TOXENV=py35
  - python: "2.7"
    env: TOXENV=py27

install:
- pip install --ignore-installed --upgrade setuptools pip tox

script:
- cd library
- tox -vv
